services:
  sapui5-app:
    build: .
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    ports:
      - "8005:8081"
    volumes:
      - .:/home/node/app
    networks:
      - sapui5-network

networks:
  sapui5-network:
    driver: bridge
