services:
  sapui5-app:
    build: .
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - CDS_AUTH_KIND=mocked
    ports:
      - "8005:8081"   # Porta exposta para fora
    volumes:
      - .:/home/node/app
    networks:
      - sapui5-network

networks:
  sapui5-network:
    driver: bridge
